// Generated by scripts/sync-verified-content.py from data/emergency_hotlines.json.
export default function HotlineBar() {
  return (
    <div className="hotline-bar">
      <div className="container">
        <div className="hotline-inner">
          <div className="hotline-items">
            <a className="hotline-item" href={'tel:911'}>
              <span>{'National emergency: 911'}</span>
            </a>
            <a className="hotline-item" href={'tel:09544199935'}>
              <span>{'APSEMO: 0954 419 9935'}</span>
            </a>
            <a className="hotline-item" href={'tel:09475700332'}>
              <span>{'Albay EMS: 0947 570 0332'}</span>
            </a>
            <a className="hotline-item" href="/contact/#emergency-hotlines">
              <span>All Albay hotlines</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
