#!/usr/bin/env python3
"""Generate the Better Albay footer logo for dark backgrounds.

`assets/images/logo/better-albay-logo.svg` is a VTracer 0.6.4 trace, so every
shape is its own `<path fill="#rrggbb">` (333 of them, with hundreds of
anti-aliasing tints).

The mark (Mayon + sun) is drawn with colourful pixels — blue and gold, high
chroma. The wordmark ("Better Albay .org") is drawn with near-black greys, low
chroma. So: any path whose fill has low chroma is wordmark/text and is
recoloured to #ffffff; every coloured path is left untouched. The original
mountain uses transparent cutouts for its slope details, so a white silhouette
is placed behind the mountain to make those details visible on a dark footer.

Verified split (scripts/analyze-logo-colors.py):
  neutral (text)  -> 127 paths, all at x 780-1405
  blue   (icon)   -> 168 paths, all at x  99- 771
  gold   (icon)   ->  38 paths, all at x 131- 517

Usage:
  python3 scripts/make-logo-text-white.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets/images/logo/better-albay-logo.svg"
OUT = ROOT / "assets/images/logo/better-albay-logo-text-white.svg"
REACT_OUT = ROOT / "react-app/public/assets/images/logo/better-albay-logo-text-white.svg"

PATH_RE = re.compile(r"<path\b[^>]*>")
FILL_RE = re.compile(r'fill="(#[0-9A-Fa-f]{3,6})"')
D_RE = re.compile(r'd="([^"]+)"')
TRANSFORM_RE = re.compile(r'transform="([^"]+)"')
CHROMA_CUTOFF = 30


def chroma(hexcolor):
    h = hexcolor.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return max(r, g, b) - min(r, g, b)


def mountain_white_base(svg):
    """Return a white copy of the mountain's outer silhouette."""
    first_path = PATH_RE.search(svg)
    if not first_path:
        sys.exit("missing mountain path in source logo")

    tag = first_path.group(0)
    d_match = D_RE.search(tag)
    transform_match = TRANSFORM_RE.search(tag)
    if not d_match or not transform_match:
        sys.exit("mountain path is missing d or transform")

    close_match = re.search(r"\sZ(?:\s|$)", d_match.group(1))
    if not close_match:
        sys.exit("mountain outer silhouette is not closed")

    outer_d = d_match.group(1)[:close_match.start() + 2]
    return (
        f'<path d="{outer_d}" fill="#ffffff" '
        f'transform="{transform_match.group(1)}"/>'
    )


def main():
    if not SRC.exists():
        sys.exit(f"missing source: {SRC}")

    svg = SRC.read_text(encoding="utf-8")
    recolored = [0]
    kept = [0]

    def repl(match):
        tag = match.group(0)
        fill_m = FILL_RE.search(tag)
        if not fill_m:
            kept[0] += 1
            return tag
        if chroma(fill_m.group(1)) <= CHROMA_CUTOFF:
            recolored[0] += 1
            return FILL_RE.sub('fill="#ffffff"', tag, count=1)
        kept[0] += 1
        return tag

    out = PATH_RE.sub(repl, svg)
    first_path = PATH_RE.search(out)
    out = out[:first_path.start()] + mountain_white_base(svg) + "\n" + out[first_path.start():]

    # Tag the file so it is obvious which variant it is when opened directly.
    out = out.replace(
        "<!-- Generator: visioncortex VTracer 0.6.4 -->",
        "<!-- Generator: visioncortex VTracer 0.6.4 -->\n"
        "<!-- Variant: white wordmark and Mayon slope accents on transparent "
        "background; icon keeps its original blue/gold colours.\n"
        "     Generated by scripts/make-logo-text-white.py from "
        "better-albay-logo.svg -->",
        1,
    )

    for target in (OUT, REACT_OUT):
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(out, encoding="utf-8")
        print(
            f"{target.relative_to(ROOT)}: "
            f"{recolored[0]} paths -> #ffffff, {kept[0]} paths kept"
        )


if __name__ == "__main__":
    main()
