#!/usr/bin/env python3
"""
Generate government/index.html from data/officials.json.
Produces semantic, accessible HTML representing all Albay provincial
executives, congressional representatives, board members, and all 18 LGUs.
"""

import json
from pathlib import Path
import html
import subprocess

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "officials.json"
TARGET_PATH = ROOT / "government" / "index.html"

# District mapping for Albay's 18 LGUs
LGU_DISTRICTS = {
    # 1st District (6 LGUs)
    "Bacacay": 1,
    "Malilipot": 1,
    "Malinao": 1,
    "Santo Domingo": 1,
    "Tabaco City": 1,
    "Tiwi": 1,
    # 2nd District (5 LGUs)
    "Camalig": 2,
    "Daraga": 2,
    "Legazpi City": 2,
    "Manito": 2,
    "Rapu-Rapu": 2,
    # 3rd District (7 LGUs)
    "Guinobatan": 3,
    "Jovellar": 3,
    "Libon": 3,
    "Ligao City": 3,
    "Oas": 3,
    "Pio Duran": 3,
    "Polangui": 3,
}

COVERAGE_BY_DISTRICT = {
    1: "Tiwi, Malinao, Tabaco City, Malilipot, Santo Domingo, Bacacay",
    2: "Legazpi City, Camalig, Daraga, Manito, Rapu-Rapu",
    3: "Ligao City, Guinobatan, Jovellar, Libon, Oas, Pio Duran, Polangui",
}

DISTRICT_ORDINALS = {
    1: "1st first",
    2: "2nd second",
    3: "3rd third",
}


def esc(s):
    return html.escape(str(s if s is not None else ""))


def build_page():
    with open(DATA_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    term = data.get("term", "2025–2028 local term / 20th Congress")
    ref_date = data.get("reference_date", "2026-09-19")
    provenance = data.get("provenance", "")
    limitations = data.get("limitations", [])
    source_pointers = data.get("source_pointers", {})
    reps = data.get("congressional_representatives", [])
    prov = data.get("provincial_government", {})
    gov = prov.get("governor", {})
    v_gov = prov.get("vice_governor", {})
    board_members = prov.get("regular_board_members", [])
    ex_officio = prov.get("additional_board_or_ex_officio_names", [])
    other_prov = data.get("other_identified_provincial_officials", [])
    cities = data.get("cities", [])
    municipalities = data.get("municipalities", [])

    total_lgus = len(cities) + len(municipalities)
    total_reps = len(reps)
    total_sp = len(board_members) + len(ex_officio)

    # Compute total councilors
    total_councilors = sum(len(c.get("city_councilors", [])) for c in cities) + sum(
        len(m.get("municipal_councilors", [])) for m in municipalities
    )
    total_documented = (
        2  # Gov, Vice Gov
        + total_reps
        + total_sp
        + len(other_prov)
        + total_lgus * 2  # Mayors, Vice Mayors
        + total_councilors
    )

    lines = []
    lines.append('<!doctype html>')
    lines.append('<html lang="en">')
    lines.append('  <head>')
    lines.append('    <meta charset="UTF-8" />')
    lines.append('    <!-- Google tag (gtag.js) -->')
    lines.append('    <script async src="https://www.googletagmanager.com/gtag/js?id=G-8777S9SP9X"></script>')
    lines.append('    <script>')
    lines.append('      window.dataLayer = window.dataLayer || [];')
    lines.append('      function gtag() {')
    lines.append('        dataLayer.push(arguments);')
    lines.append('      }')
    lines.append("      gtag('js', new Date());")
    lines.append("      gtag('config', 'G-8777S9SP9X');")
    lines.append('    </script>')
    lines.append('    <meta name="viewport" content="width=device-width, initial-scale=1.0" />')
    lines.append('    <meta')
    lines.append('      name="description"')
    lines.append(
        '      content="Official government structure and leadership directory for the Province of Albay. Meet Governor Noel E. Rosal, Vice Governor Farida \'Diday\' Co, Congressional Representatives, Sangguniang Panlalawigan members, and elected officials across 18 cities and municipalities."'
    )
    lines.append('    />')
    lines.append('    <meta name="author" content="Jayson (jsonrls)" />')
    lines.append('    <meta')
    lines.append('      name="keywords"')
    lines.append(
        '      content="Albay provincial government, Albay officials, Governor Noel Rosal, Vice Governor Farida Co, Sangguniang Panlalawigan, Albay congress, Legazpi City, Ligao City, Tabaco City, Albay municipalities, Albay directory, 2025-2028 officials"'
    )
    lines.append('    />')
    lines.append('    <meta name="robots" content="index, follow" />')
    lines.append('    <link rel="canonical" href="https://betteralbay.org/government/" />')
    lines.append('')
    lines.append('    <!-- Open Graph -->')
    lines.append('    <meta property="og:type" content="website" />')
    lines.append('    <meta property="og:url" content="https://betteralbay.org/government/" />')
    lines.append('    <meta property="og:title" content="Government Structure & Officials | BetterAlbay.org" />')
    lines.append('    <meta')
    lines.append('      property="og:description"')
    lines.append(
        '      content="Official directory of the Province of Albay: Congressional Representatives, Governor Noel E. Rosal, Vice Governor Farida \'Diday\' Co, Sangguniang Panlalawigan board members, and 18 cities and municipalities."'
    )
    lines.append('    />')
    lines.append('    <meta')
    lines.append('      property="og:image"')
    lines.append('      content="https://betteralbay.org/assets/images/banners/opengraph.png"')
    lines.append('    />')
    lines.append('    <meta property="og:image:width" content="1200" />')
    lines.append('    <meta property="og:image:height" content="630" />')
    lines.append('    <meta property="og:image:type" content="image/png" />')
    lines.append('    <meta')
    lines.append('      property="og:image:secure_url"')
    lines.append('      content="https://betteralbay.org/assets/images/banners/opengraph.png"')
    lines.append('    />')
    lines.append('    <meta property="og:site_name" content="BetterAlbay.org" />')
    lines.append('')
    lines.append('    <!-- Twitter -->')
    lines.append('    <meta name="twitter:card" content="summary_large_image" />')
    lines.append('    <meta')
    lines.append('      name="twitter:image"')
    lines.append('      content="https://betteralbay.org/assets/images/banners/opengraph.png"')
    lines.append('    />')
    lines.append('    <meta name="twitter:title" content="Government Structure & Officials | BetterAlbay.org" />')
    lines.append('    <meta')
    lines.append('      name="twitter:description"')
    lines.append(
        '      content="Official directory of the Province of Albay: Congressional Representatives, Governor Noel E. Rosal, Vice Governor Farida \'Diday\' Co, Sangguniang Panlalawigan board members, and 18 cities and municipalities."'
    )
    lines.append('    />')
    lines.append('')
    lines.append('    <!-- Theme Color -->')
    lines.append('    <meta name="theme-color" content="#0032a0" />')
    lines.append('')
    lines.append('    <title>Government Structure &amp; Officials | BetterAlbay.org</title>')
    lines.append('')
    lines.append('    <!-- Favicon -->')
    lines.append('    <link rel="icon" type="image/svg+xml" href="../assets/images/logo/favicon.ico" />')
    lines.append('    <link rel="icon" type="image/x-icon" href="../assets/images/logo/favicon.ico" />')
    lines.append('    <link rel="apple-touch-icon" href="../assets/images/logo/favicon.ico" />')
    lines.append('')
    lines.append('    <!-- Fonts & Icons -->')
    lines.append('    <link rel="preconnect" href="https://fonts.googleapis.com" />')
    lines.append('    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />')
    lines.append('    <link rel="preconnect" href="https://cdn.jsdelivr.net" />')
    lines.append('    <link rel="dns-prefetch" href="https://cdn.jsdelivr.net" />')
    lines.append('    <link')
    lines.append('      href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"')
    lines.append('      rel="stylesheet"')
    lines.append('    />')
    lines.append('    <link')
    lines.append('      rel="stylesheet"')
    lines.append('      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"')
    lines.append('    />')
    lines.append('')
    lines.append('    <!-- Schema.org JSON-LD -->')
    lines.append('    <script type="application/ld+json">')
    lines.append('      {')
    lines.append('        "@context": "https://schema.org",')
    lines.append('        "@type": "BreadcrumbList",')
    lines.append('        "itemListElement": [')
    lines.append('          {')
    lines.append('            "@type": "ListItem",')
    lines.append('            "position": 1,')
    lines.append('            "name": "Home",')
    lines.append('            "item": "https://betteralbay.org/"')
    lines.append('          },')
    lines.append('          {')
    lines.append('            "@type": "ListItem",')
    lines.append('            "position": 2,')
    lines.append('            "name": "Government"')
    lines.append('          }')
    lines.append('        ]')
    lines.append('      }')
    lines.append('    </script>')
    lines.append('')
    lines.append('    <!-- Styles -->')
    lines.append('    <link rel="stylesheet" href="../assets/css/style.css" />')
    lines.append('    <link rel="stylesheet" href="../assets/css/responsive.css" />')
    lines.append('    <link rel="stylesheet" href="../assets/css/accessibility.css" />')
    lines.append('    <link rel="stylesheet" href="../assets/css/footer.css" />')
    lines.append('    <link rel="stylesheet" href="../assets/css/directory.css" />')
    lines.append('')
    lines.append('    <style>')
    lines.append('      :root {')
    lines.append('        --color-primary-solid: var(--color-primary, #0032a0);')
    lines.append('        --color-border: #e2e8f0;')
    lines.append('        --color-bg-muted: #f1f5f9;')
    lines.append('        --radius-pill: 50px;')
    lines.append('        --radius-md: 8px;')
    lines.append('        --radius-sm: 6px;')
    lines.append('        --fw-medium: 500;')
    lines.append('      }')
    lines.append('      .gov-section-badge {')
    lines.append('        display: inline-flex;')
    lines.append('        align-items: center;')
    lines.append('        gap: 8px;')
    lines.append('        background: var(--color-primary-solid);')
    lines.append('        color: #fff;')
    lines.append('        padding: 8px 20px;')
    lines.append('        border-radius: var(--radius-pill);')
    lines.append('        font-size: 0.875rem;')
    lines.append('        font-weight: var(--fw-medium);')
    lines.append('        margin-bottom: var(--spacing-sm);')
    lines.append('      }')
    lines.append('      .district-nav {')
    lines.append('        display: flex;')
    lines.append('        flex-wrap: wrap;')
    lines.append('        gap: 8px;')
    lines.append('        justify-content: center;')
    lines.append('        margin-bottom: var(--spacing-lg);')
    lines.append('      }')
    lines.append('      .district-btn {')
    lines.append('        padding: 8px 18px;')
    lines.append('        border-radius: var(--radius-pill);')
    lines.append('        border: 1px solid var(--color-border);')
    lines.append('        background: var(--color-white);')
    lines.append('        color: var(--color-text);')
    lines.append('        font-size: 0.875rem;')
    lines.append('        font-weight: 600;')
    lines.append('        cursor: pointer;')
    lines.append('        transition: all 0.2s ease;')
    lines.append('      }')
    lines.append('      .district-btn:hover {')
    lines.append('        border-color: var(--color-primary);')
    lines.append('        color: var(--color-primary);')
    lines.append('      }')
    lines.append('      .district-btn.active {')
    lines.append('        background: var(--color-primary);')
    lines.append('        border-color: var(--color-primary);')
    lines.append('        color: #fff;')
    lines.append('      }')
    lines.append('      .appointed-strip {')
    lines.append('        margin-top: var(--spacing-lg);')
    lines.append('        padding: 16px 20px;')
    lines.append('        background: var(--color-white);')
    lines.append('        border: 1px solid var(--color-border);')
    lines.append('        border-radius: 12px;')
    lines.append('        display: flex;')
    lines.append('        flex-wrap: wrap;')
    lines.append('        gap: 16px;')
    lines.append('        justify-content: space-around;')
    lines.append('        align-items: center;')
    lines.append('      }')
    lines.append('      .appointed-item {')
    lines.append('        display: flex;')
    lines.append('        align-items: center;')
    lines.append('        gap: 12px;')
    lines.append('      }')
    lines.append('      .appointed-icon {')
    lines.append('        width: 38px;')
    lines.append('        height: 38px;')
    lines.append('        border-radius: 50%;')
    lines.append('        background: rgba(0, 50, 160, 0.08);')
    lines.append('        color: var(--color-primary);')
    lines.append('        display: flex;')
    lines.append('        align-items: center;')
    lines.append('        justify-content: center;')
    lines.append('        font-size: 1.1rem;')
    lines.append('      }')
    lines.append('      .rep-card {')
    lines.append('        background: var(--color-white);')
    lines.append('        border: 1px solid var(--color-border);')
    lines.append('        border-radius: 16px;')
    lines.append('        padding: 24px;')
    lines.append('        display: flex;')
    lines.append('        flex-direction: column;')
    lines.append('        gap: 12px;')
    lines.append('        transition: transform 0.2s ease, box-shadow 0.2s ease;')
    lines.append('      }')
    lines.append('      .rep-card:hover {')
    lines.append('        transform: translateY(-3px);')
    lines.append('        box-shadow: var(--shadow-md);')
    lines.append('        border-color: rgba(0, 50, 160, 0.2);')
    lines.append('      }')
    lines.append('      .rep-badge {')
    lines.append('        display: inline-block;')
    lines.append('        padding: 4px 12px;')
    lines.append('        border-radius: 50px;')
    lines.append('        font-size: 0.75rem;')
    lines.append('        font-weight: 700;')
    lines.append('        text-transform: uppercase;')
    lines.append('        letter-spacing: 0.5px;')
    lines.append('        background: rgba(0, 50, 160, 0.1);')
    lines.append('        color: var(--color-primary);')
    lines.append('      }')
    lines.append('      .rep-name {')
    lines.append('        font-size: 1.25rem;')
    lines.append('        font-weight: 700;')
    lines.append('        margin: 0;')
    lines.append('        color: var(--color-text);')
    lines.append('      }')
    lines.append('      .rep-jurisdiction {')
    lines.append('        font-size: 0.875rem;')
    lines.append('        color: var(--color-text-light);')
    lines.append('        line-height: 1.5;')
    lines.append('      }')
    lines.append('      .rep-verification {')
    lines.append('        font-size: 0.75rem;')
    lines.append('        color: var(--color-text-light);')
    lines.append('        border-top: 1px solid rgba(0, 0, 0, 0.06);')
    lines.append('        padding-top: 8px;')
    lines.append('        margin-top: auto;')
    lines.append('      }')
    lines.append('      .councilors-collapse {')
    lines.append('        margin-top: 10px;')
    lines.append('        padding-top: 12px;')
    lines.append('        border-top: 1px dashed var(--color-border);')
    lines.append('        width: 100%;')
    lines.append('      }')
    lines.append('      details.councilors-collapse summary.council-toggle-btn {')
    lines.append('        list-style: none;')
    lines.append('        cursor: pointer;')
    lines.append('        user-select: none;')
    lines.append('        width: 100%;')
    lines.append('        box-sizing: border-box;')
    lines.append('        display: flex;')
    lines.append('        align-items: center;')
    lines.append('        justify-content: center;')
    lines.append('      }')
    lines.append('      details.councilors-collapse summary.council-toggle-btn::-webkit-details-marker,')
    lines.append('      details.councilors-collapse summary.council-toggle-btn::marker {')
    lines.append('        display: none;')
    lines.append('      }')
    lines.append('      details.councilors-collapse[open] .toggle-icon {')
    lines.append('        transform: rotate(180deg);')
    lines.append('      }')
    lines.append('      .toggle-icon {')
    lines.append('        transition: transform 0.2s ease;')
    lines.append('        margin-left: 2px;')
    lines.append('      }')
    lines.append('      .councilor-tag-list {')
    lines.append('        display: flex;')
    lines.append('        flex-wrap: wrap;')
    lines.append('        gap: 6px;')
    lines.append('        margin-top: 8px;')
    lines.append('      }')
    lines.append('      .councilor-tag {')
    lines.append('        font-size: 0.8125rem;')
    lines.append('        background: var(--color-bg-alt);')
    lines.append('        border: 1px solid rgba(0, 0, 0, 0.06);')
    lines.append('        padding: 4px 10px;')
    lines.append('        border-radius: 6px;')
    lines.append('        color: var(--color-text);')
    lines.append('      }')
    lines.append('      .councilor-tag.match {')
    lines.append('        background: #fef3c7;')
    lines.append('        border-color: #f59e0b;')
    lines.append('        font-weight: 600;')
    lines.append('      }')
    lines.append('      .council-toggle-btn {')
    lines.append('        background: var(--color-bg-alt);')
    lines.append('        border: 1px solid rgba(0, 50, 160, 0.18);')
    lines.append('        color: var(--color-primary);')
    lines.append('        padding: 9px 14px;')
    lines.append('        border-radius: 8px;')
    lines.append('        font-size: 0.8125rem;')
    lines.append('        font-weight: 600;')
    lines.append('        cursor: pointer;')
    lines.append('        display: flex;')
    lines.append('        align-items: center;')
    lines.append('        justify-content: center;')
    lines.append('        gap: 8px;')
    lines.append('        width: 100%;')
    lines.append('        box-sizing: border-box;')
    lines.append('        transition: background-color 0.2s ease, border-color 0.2s ease;')
    lines.append('      }')
    lines.append('      .council-toggle-btn:hover {')
    lines.append('        background: rgba(0, 50, 160, 0.08);')
    lines.append('        border-color: var(--color-primary);')
    lines.append('      }')
    lines.append('      .lgu-links {')
    lines.append('        display: flex;')
    lines.append('        gap: 8px;')
    lines.append('        margin-top: auto;')
    lines.append('        width: 100%;')
    lines.append('      }')
    lines.append('      .lgu-links a {')
    lines.append('        flex: 1 1 0;')
    lines.append('        min-width: 0;')
    lines.append('        display: inline-flex;')
    lines.append('        align-items: center;')
    lines.append('        justify-content: center;')
    lines.append('        gap: 6px;')
    lines.append('        font-size: 0.8125rem;')
    lines.append('        font-weight: 600;')
    lines.append('        padding: 8px 12px;')
    lines.append('        border-radius: 8px;')
    lines.append('        background: rgba(0, 50, 160, 0.07);')
    lines.append('        color: var(--color-primary);')
    lines.append('        text-decoration: none;')
    lines.append('        text-align: center;')
    lines.append('        white-space: nowrap;')
    lines.append('        transition: background 0.2s ease, color 0.2s ease;')
    lines.append('      }')
    lines.append('      .lgu-links a:hover {')
    lines.append('        background: rgba(0, 50, 160, 0.14);')
    lines.append('      }')
    lines.append('      .lead-pair {')
    lines.append('        display: flex;')
    lines.append('        flex-direction: column;')
    lines.append('        gap: 8px;')
    lines.append('      }')
    lines.append('      .lead-role {')
    lines.append('        display: flex;')
    lines.append('        align-items: center;')
    lines.append('        gap: 8px;')
    lines.append('        font-size: 0.875rem;')
    lines.append('        color: var(--color-text);')
    lines.append('        background: var(--color-bg-alt);')
    lines.append('        padding: 8px 12px;')
    lines.append('        border-radius: 8px;')
    lines.append('      }')
    lines.append('      .lead-role strong {')
    lines.append('        color: var(--color-text);')
    lines.append('      }')
    lines.append('      .sp-presiding {')
    lines.append('        background: linear-gradient(135deg, rgba(0, 50, 160, 0.05) 0%, rgba(0, 119, 190, 0.05) 100%);')
    lines.append('        border: 1px solid rgba(0, 50, 160, 0.15);')
    lines.append('        border-radius: 12px;')
    lines.append('        padding: 16px 20px;')
    lines.append('        margin-bottom: var(--spacing-lg);')
    lines.append('        display: flex;')
    lines.append('        align-items: center;')
    lines.append('        gap: 16px;')
    lines.append('        flex-wrap: wrap;')
    lines.append('        justify-content: space-between;')
    lines.append('      }')
    lines.append('    </style>')
    lines.append('  </head>')
    lines.append('')
    lines.append('  <body>')
    lines.append('    <a href="#main-content" class="skip-link" data-i18n="gov-skip-to-main-content">Skip to main content</a>')
    lines.append('')
    lines.append('    <!-- Hotline Bar -->')
    lines.append('    <div class="hotline-bar">')
    lines.append('      <div class="container">')
    lines.append('        <div class="hotline-inner">')
    lines.append('          <!-- prettier-ignore -->')
    lines.append(
        '          <div class="hotline-items"><a href="tel:911" class="hotline-item"><span data-i18n="hotline-bar-national">National emergency: 911</span></a><a href="tel:09544199935" class="hotline-item"><span>APSEMO: 0954 419 9935</span></a><a href="tel:09475700332" class="hotline-item"><span>Albay EMS: 0947 570 0332</span></a><a href="/contact/#emergency-hotlines" class="hotline-item"><span data-i18n="hotline-bar-all">All Albay hotlines</span></a></div>'
    )
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </div>')
    lines.append('')
    lines.append('    <!-- Header -->')
    lines.append('    <header class="site-header">')
    lines.append('      <div class="container header-inner">')
    lines.append('        <div class="logo-container">')
    lines.append('          <a href="../">')
    lines.append('            <img')
    lines.append('              src="../assets/images/logo/better-albay-logo.svg"')
    lines.append('              alt="Province of Albay Logo"')
    lines.append('              class="logo-img"')
    lines.append('              width="113"')
    lines.append('              height="40"')
    lines.append('            />')
    lines.append('          </a>')
    lines.append('        </div>')
    lines.append('')
    lines.append('        <nav class="main-nav" aria-label="Main Navigation">')
    lines.append('          <ul>')
    lines.append('            <li><a href="../" data-i18n="nav-home">Home</a></li>')
    lines.append('            <li class="has-dropdown">')
    lines.append('              <a href="../services/" data-i18n="nav-services" aria-haspopup="true" aria-expanded="false">Services</a>')
    lines.append('              <ul class="dropdown-menu">')
    lines.append('                <li><a href="../services/certificates" data-i18n="gov-certificates">Certificates</a></li>')
    lines.append('                <li><a href="../services/business" data-i18n="gov-business">Business</a></li>')
    lines.append('                <li><a href="../services/tax-payments" data-i18n="gov-tax-payments">Tax Payments</a></li>')
    lines.append('                <li><a href="../services/social-services" data-i18n="gov-social-services">Social Services</a></li>')
    lines.append('                <li><a href="../services/health" data-i18n="gov-health">Health</a></li>')
    lines.append('                <li><a href="../services/agriculture" data-i18n="gov-agriculture">Agriculture</a></li>')
    lines.append('                <li><a href="../services/infrastructure" data-i18n="gov-infrastructure">Infrastructure</a></li>')
    lines.append('                <li><a href="../services/education" data-i18n="gov-education">Education</a></li>')
    lines.append('                <li><a href="../services/public-safety" data-i18n="gov-public-safety">Public Safety</a></li>')
    lines.append('                <li><a href="../services/environment" data-i18n="gov-environment">Environment</a></li>')
    lines.append('              </ul>')
    lines.append('            </li>')
    lines.append('            <li><a href="./" class="active" data-i18n="nav-government">Government</a></li>')
    lines.append('            <li><a href="../statistics/" data-i18n="nav-statistics">Statistics</a></li>')
    lines.append('            <li class="has-dropdown">')
    lines.append('              <a href="../legislative/" data-i18n="nav-legislative" aria-haspopup="true" aria-expanded="false">Legislative</a>')
    lines.append('              <ul class="dropdown-menu">')
    lines.append('                <li><a href="../legislative/ordinance-framework" data-i18n="gov-ordinance-framework">Ordinance Framework</a></li>')
    lines.append('                <li><a href="../legislative/resolution-framework" data-i18n="gov-resolution-framework">Resolution Framework</a></li>')
    lines.append('              </ul>')
    lines.append('            </li>')
    lines.append('            <li><a href="../budget/" data-i18n="nav-transparency">Transparency</a></li>')
    lines.append('            <li><a href="../contact/" data-i18n="nav-contact">Contact</a></li>')
    lines.append('          </ul>')
    lines.append('        </nav>')
    lines.append('')
    lines.append('        <div class="header-actions">')
    lines.append('          <div class="lang-selector">')
    lines.append('            <button class="btn btn-secondary btn-sm lang-btn" data-lang="en" aria-label="Switch to English">EN</button>')
    lines.append('            <button class="btn btn-secondary btn-sm lang-btn" data-lang="fil" aria-label="Switch to Filipino">FIL</button>')
    lines.append('            <button class="btn btn-secondary btn-sm lang-btn" data-lang="bcl" aria-label="Switch to Bikol">BCL</button>')
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </header>')
    lines.append('')
    lines.append('    <!-- Real-Time Info Bar -->')
    lines.append('    <div class="info-bar" role="complementary" aria-label="Real-time information">')
    lines.append('      <div class="container">')
    lines.append('        <div class="info-bar-inner">')
    lines.append('          <div class="info-bar-item info-bar-rates" aria-label="Exchange rates">')
    lines.append('            <i class="bi bi-currency-exchange"></i>')
    lines.append('            <span class="rate-rotator">')
    lines.append('              <span class="rate-display">1 USD = ₱ --</span>')
    lines.append('            </span>')
    lines.append('          </div>')
    lines.append('          <div class="info-bar-item info-bar-weather" aria-label="Current weather in Albay">')
    lines.append('            <i class="bi bi-thermometer-half"></i>')
    lines.append('            <span class="weather-location">Albay</span>')
    lines.append('            <span class="weather-temp">--°C</span>')
    lines.append('          </div>')
    lines.append('          <div class="info-bar-item info-bar-datetime" aria-label="Philippine Date and Time">')
    lines.append('            <i class="bi bi-calendar3"></i>')
    lines.append('            <span class="date-value">--- --, ----</span>')
    lines.append('            <span class="datetime-separator">•</span>')
    lines.append('            <i class="bi bi-clock"></i>')
    lines.append('            <span class="time-value">--:-- --</span>')
    lines.append('            <span class="time-label">PHT</span>')
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </div>')
    lines.append('')
    lines.append('    <main id="main-content">')
    lines.append('      <!-- Breadcrumbs -->')
    lines.append('      <div class="container">')
    lines.append('        <nav class="breadcrumbs" aria-label="Breadcrumb">')
    lines.append('          <a href="../" data-i18n="nav-home">Home</a> <span>/</span>')
    lines.append('          <span aria-current="page" data-i18n="nav-government">Government</span>')
    lines.append('        </nav>')
    lines.append('      </div>')
    lines.append('')
    lines.append('      <!-- Page Header -->')
    lines.append('      <section class="page-header">')
    lines.append('        <div class="container">')
    lines.append('          <div class="page-header-content">')
    lines.append('            <span class="page-header-badge">')
    lines.append('              <i class="bi bi-building-fill"></i> <span data-i18n="gov-page-badge">Government Directory</span>')
    lines.append('            </span>')
    lines.append('            <h1 data-i18n="gov-page-title">Government Structure &amp; Officials</h1>')
    lines.append(
        '            <p class="page-header-desc" data-i18n="gov-page-desc">Meet the leadership and offices serving Albay</p>'
    )
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </section>')
    lines.append('')
    lines.append('      <!-- Stat Strip -->')
    lines.append('      <section class="section dir-stats-section" aria-label="Government coverage summary">')
    lines.append('        <div class="container">')
    lines.append('          <div class="dir-stats">')
    lines.append('            <div class="dir-stat">')
    lines.append(f'              <span class="dir-stat-value">{total_reps}</span>')
    lines.append('              <span class="dir-stat-label" data-i18n="gov-stat-districts">Congressional Districts</span>')
    lines.append('            </div>')
    lines.append('            <div class="dir-stat">')
    lines.append('              <span class="dir-stat-value">2</span>')
    lines.append('              <span class="dir-stat-label" data-i18n="gov-stat-execs">Provincial Executives</span>')
    lines.append('            </div>')
    lines.append('            <div class="dir-stat">')
    lines.append(f'              <span class="dir-stat-value">{total_sp}</span>')
    lines.append('              <span class="dir-stat-label" data-i18n="gov-stat-sp">Provincial Board Members</span>')
    lines.append('            </div>')
    lines.append('            <div class="dir-stat">')
    lines.append(f'              <span class="dir-stat-value">{total_lgus}</span>')
    lines.append('              <span class="dir-stat-label" data-i18n="gov-stat-lgus">Cities &amp; Municipalities</span>')
    lines.append('            </div>')
    lines.append('            <div class="dir-stat">')
    lines.append(f'              <span class="dir-stat-value">{total_documented}+</span>')
    lines.append('              <span class="dir-stat-label" data-i18n="gov-stat-officials">Documented Officials</span>')
    lines.append('            </div>')
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </section>')
    lines.append('')
    lines.append('      <!-- Scope and Limitations Note -->')
    lines.append('      <section class="section" style="padding-top: 0; padding-bottom: var(--spacing-md)">')
    lines.append('        <div class="container">')
    lines.append('          <div class="dir-note">')
    lines.append('            <i class="bi bi-info-circle-fill" aria-hidden="true"></i>')
    lines.append('            <div>')
    lines.append(
        f'              <strong>Scope &amp; Data Verification Notice ({esc(ref_date)}).</strong> '
        'This directory is sourced from <code>data/officials.json</code>, consolidating the 20th Congress House of Representatives roster, official reporting on the Provincial Government of Albay, and local government rosters for the 2025–2028 term. '
        'For official COMELEC records and gazetted appointments, verify directly with the respective local government unit, the '
        '<a href="https://www.comelec.gov.ph/" target="_blank" rel="noopener noreferrer">Commission on Elections</a>, or the '
        '<a href="https://dilg.gov.ph/" target="_blank" rel="noopener noreferrer">Department of the Interior and Local Government (DILG)</a>. '
        'Looking for village-level data? Visit the <a href="barangays.html">Albay 720-Barangay Directory</a>.'
    )
    lines.append('            </div>')
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </section>')
    lines.append('')
    lines.append('      <!-- Section 1: Provincial Executive Leadership -->')
    lines.append('      <section class="section" id="provincial-executive" style="background: var(--color-bg-alt)">')
    lines.append('        <div class="container">')
    lines.append('          <div class="text-center" style="margin-bottom: var(--spacing-xl)">')
    lines.append('            <span class="gov-section-badge">')
    lines.append('              <i class="bi bi-star-fill"></i> <span data-i18n="gov-section-exec">Executive Branch</span>')
    lines.append('            </span>')
    lines.append('            <h2 style="font-size: 1.75rem; margin-bottom: var(--spacing-xs)" data-i18n="gov-section-exec-title">')
    lines.append('              Provincial Government Leadership')
    lines.append('            </h2>')
    lines.append('            <p style="color: var(--color-text-light)" data-i18n="gov-section-exec-desc">')
    lines.append('              The executive leadership steering the Provincial Government of Albay (PGA)')
    lines.append('            </p>')
    lines.append('          </div>')
    lines.append('')
    lines.append('          <div class="grid grid-2" style="gap: var(--spacing-lg)">')
    # Governor
    gov_name = gov.get("name", "Noel E. Rosal")
    gov_pos = gov.get("position", "Governor")
    gov_verif = gov.get("verification", "")
    lines.append('            <div class="executive-card">')
    lines.append('              <div class="executive-card-header">')
    lines.append(f'                <span class="executive-badge">Provincial {esc(gov_pos)}</span>')
    lines.append(f'                <h3 class="executive-name">Hon. {esc(gov_name)}</h3>')
    lines.append('              </div>')
    lines.append('              <div class="executive-card-body">')
    lines.append('                <div class="executive-contacts">')
    lines.append('                  <a href="mailto:pgasecretariat@gmail.com">')
    lines.append('                    <i class="bi bi-envelope"></i> <span>pgasecretariat@gmail.com</span>')
    lines.append('                  </a>')
    lines.append('                  <a href="tel:0527426377">')
    lines.append('                    <i class="bi bi-telephone"></i> <span>(052) 742-6377</span>')
    lines.append('                  </a>')
    lines.append('                  <span>')
    lines.append('                    <i class="bi bi-geo-alt"></i> <span>Albay Provincial Capitol, Legazpi City</span>')
    lines.append('                  </span>')
    lines.append('                  <span>')
    lines.append('                    <i class="bi bi-clock"></i> <span>Mon–Fri: 8:00 AM – 5:00 PM</span>')
    lines.append('                  </span>')
    lines.append('                </div>')
    if gov_verif:
        lines.append(f'                <div class="rep-verification" style="margin-top: 12px; font-size: 0.75rem; color: var(--color-text-light)"><i class="bi bi-shield-check" style="color: var(--color-success)"></i> {esc(gov_verif)}</div>')
    lines.append('              </div>')
    lines.append('            </div>')
    # Vice Governor
    v_gov_name = v_gov.get("name", "Farida “Diday” S. Co")
    v_gov_pos = v_gov.get("position", "Vice Governor")
    v_gov_verif = v_gov.get("verification", "")
    lines.append('            <div class="executive-card">')
    lines.append('              <div class="executive-card-header">')
    lines.append(f'                <span class="executive-badge">Provincial {esc(v_gov_pos)}</span>')
    lines.append(f'                <h3 class="executive-name">Hon. {esc(v_gov_name)}</h3>')
    lines.append('              </div>')
    lines.append('              <div class="executive-card-body">')
    lines.append('                <div class="executive-contacts">')
    lines.append('                  <a href="mailto:vicepgasecretariat@gmail.com">')
    lines.append('                    <i class="bi bi-envelope"></i> <span>vicepgasecretariat@gmail.com</span>')
    lines.append('                  </a>')
    lines.append('                  <a href="tel:09268284392">')
    lines.append('                    <i class="bi bi-phone"></i> <span>(0926) 828-4392</span>')
    lines.append('                  </a>')
    lines.append('                  <span>')
    lines.append('                    <i class="bi bi-geo-alt"></i> <span>Office of the Vice Governor, Capitol</span>')
    lines.append('                  </span>')
    lines.append('                  <span>')
    lines.append('                    <i class="bi bi-clock"></i> <span>Mon–Fri: 8:00 AM – 5:00 PM</span>')
    lines.append('                  </span>')
    lines.append('                </div>')
    if v_gov_verif:
        lines.append(f'                <div class="rep-verification" style="margin-top: 12px; font-size: 0.75rem; color: var(--color-text-light)"><i class="bi bi-shield-check" style="color: var(--color-success)"></i> {esc(v_gov_verif)}</div>')
    lines.append('              </div>')
    lines.append('            </div>')
    lines.append('          </div>')
    lines.append('')
    # Appointed Officials
    if other_prov:
        lines.append('          <div class="appointed-strip">')
        for op in other_prov:
            lines.append('            <div class="appointed-item">')
            lines.append('              <div class="appointed-icon"><i class="bi bi-person-badge"></i></div>')
            lines.append('              <div>')
            lines.append(f'                <strong style="display: block; color: var(--color-text)">{esc(op.get("name"))}</strong>')
            lines.append(f'                <span style="font-size: 0.8125rem; color: var(--color-text-light)">{esc(op.get("position"))}</span>')
            op_verif = op.get("verification")
            if op_verif:
                lines.append(f'                <span style="display: block; font-size: 0.75rem; color: var(--color-text-light); margin-top: 2px"><i class="bi bi-shield-check" style="color: var(--color-success)"></i> {esc(op_verif)}</span>')
            lines.append('              </div>')
            lines.append('            </div>')
        lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </section>')
    lines.append('')
    lines.append('      <!-- Section 2: Congressional Representatives -->')
    lines.append('      <section class="section" id="congressional-representatives">')
    lines.append('        <div class="container">')
    lines.append('          <div class="text-center" style="margin-bottom: var(--spacing-xl)">')
    lines.append('            <span class="gov-section-badge">')
    lines.append('              <i class="bi bi-bank"></i> <span data-i18n="gov-section-congress-badge">National Representation</span>')
    lines.append('            </span>')
    lines.append('            <h2 style="font-size: 1.75rem; margin-bottom: var(--spacing-xs)" data-i18n="gov-section-congress-title">')
    lines.append('              Congressional Representatives')
    lines.append('            </h2>')
    lines.append('            <p style="color: var(--color-text-light)" data-i18n="gov-section-congress-desc">')
    lines.append('              Albay members of the House of Representatives (20th Congress of the Philippines)')
    lines.append('            </p>')
    lines.append('          </div>')
    lines.append('')
    lines.append('          <div class="grid grid-3" style="gap: var(--spacing-lg)">')
    for rep in reps:
        dist = rep.get("district")
        name = rep.get("name")
        pos = rep.get("position", "Representative")
        verif = rep.get("verification", "")
        coverage = COVERAGE_BY_DISTRICT.get(dist, "")
        lines.append('            <div class="rep-card">')
        lines.append('              <div>')
        lines.append(f'                <span class="rep-badge">District {esc(dist)}</span>')
        lines.append(f'                <h3 class="rep-name">Hon. {esc(name)}</h3>')
        lines.append(f'                <span style="font-size: 0.875rem; font-weight: 600; color: var(--color-primary)">{esc(pos)}</span>')
        lines.append('              </div>')
        lines.append(f'              <p class="rep-jurisdiction"><i class="bi bi-geo-alt" style="color: var(--color-primary)"></i> <strong>Coverage:</strong> {esc(coverage)}</p>')
        if verif:
            lines.append(f'              <div class="rep-verification"><i class="bi bi-shield-check" style="color: var(--color-success)"></i> {esc(verif)}</div>')
        lines.append('            </div>')
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </section>')
    lines.append('')
    lines.append('      <!-- Section 3: Sangguniang Panlalawigan Members -->')
    lines.append('      <section class="section" id="provincial-board" style="background: var(--color-bg-alt)">')
    lines.append('        <div class="container">')
    lines.append('          <div class="text-center" style="margin-bottom: var(--spacing-xl)">')
    lines.append('            <span class="gov-section-badge">')
    lines.append('              <i class="bi bi-people-fill"></i> <span data-i18n="gov-section-leg">Legislative Branch</span>')
    lines.append('            </span>')
    lines.append('            <h2 style="font-size: 1.75rem; margin-bottom: var(--spacing-xs)" data-i18n="gov-section-sp-heading">')
    lines.append('              Sangguniang Panlalawigan Members')
    lines.append('            </h2>')
    lines.append('            <p style="color: var(--color-text-light)" data-i18n="gov-section-sp-desc">')
    lines.append('              Provincial board members enacting ordinances, resolutions, and budgets for Albay')
    lines.append('            </p>')
    lines.append('          </div>')
    lines.append('')
    # Presiding officer banner
    lines.append('          <div class="sp-presiding">')
    lines.append('            <div style="display: flex; align-items: center; gap: 12px">')
    lines.append('              <div class="appointed-icon" style="background: var(--color-primary); color: #fff">')
    lines.append('                <i class="bi bi-hammer"></i>')
    lines.append('              </div>')
    lines.append('              <div>')
    lines.append(f'                <strong style="font-size: 1.125rem; color: var(--color-text)">Hon. {esc(v_gov_name)}</strong>')
    lines.append('                <div style="font-size: 0.8125rem; color: var(--color-text-light)" data-i18n="gov-vgov-presiding-desc">')
    lines.append('                  Vice Governor &bull; Ex-officio Presiding Officer of the Sangguniang Panlalawigan')
    lines.append('                </div>')
    lines.append('              </div>')
    lines.append('            </div>')
    lines.append('            <span class="pill pill-city" style="background: var(--color-primary); color: #fff" data-i18n="gov-badge-presiding-officer">Presiding Officer</span>')
    lines.append('          </div>')
    lines.append('')
    # District filter navigation for board members
    lines.append('          <div class="district-nav" role="tablist" aria-label="Provincial board district filter">')
    lines.append('            <button type="button" class="district-btn active" data-sp-filter="all" role="tab" aria-selected="true" data-i18n="gov-sp-filter-all">All Seats (12)</button>')
    lines.append('            <button type="button" class="district-btn" data-sp-filter="1" role="tab" aria-selected="false" data-i18n="gov-sp-filter-1">1st District (3)</button>')
    lines.append('            <button type="button" class="district-btn" data-sp-filter="2" role="tab" aria-selected="false" data-i18n="gov-sp-filter-2">2nd District (3)</button>')
    lines.append('            <button type="button" class="district-btn" data-sp-filter="3" role="tab" aria-selected="false" data-i18n="gov-sp-filter-3">3rd District (4)</button>')
    lines.append('            <button type="button" class="district-btn" data-sp-filter="ex" role="tab" aria-selected="false" data-i18n="gov-sp-filter-ex">Ex-Officio &amp; Others (2)</button>')
    lines.append('          </div>')
    lines.append('')
    # Board members grid
    lines.append('          <div id="sp-grid" class="grid grid-3" style="gap: var(--spacing-md)">')
    for bm in board_members:
        dist = bm.get("district")
        name = bm.get("name")
        pos = bm.get("position", "Provincial Board Member")
        verif = bm.get("verification", "")
        lines.append(f'            <div class="councilor-card sp-card" data-district="{esc(dist)}">')
        lines.append(f'              <span class="councilor-badge">District {esc(dist)} Board Member</span>')
        lines.append(f'              <h3 class="councilor-name" style="font-size: 1.125rem; margin: 8px 0 4px">Hon. {esc(name)}</h3>')
        lines.append(f'              <p class="councilor-committees" style="font-size: 0.8125rem; color: var(--color-text-light)">')
        lines.append(f'                Sangguniang Panlalawigan &bull; District {esc(dist)}')
        lines.append('              </p>')
        if verif:
            lines.append(f'              <div style="font-size: 0.75rem; color: var(--color-text-light); border-top: 1px solid rgba(0,0,0,0.05); padding-top: 6px; margin-top: 8px"><i class="bi bi-check-circle" style="color: var(--color-success)"></i> {esc(verif)}</div>')
        lines.append('            </div>')
    for exo in ex_officio:
        name = exo.get("name")
        pos = exo.get("position", "Provincial Board Member")
        verif = exo.get("verification", "")
        lines.append('            <div class="councilor-card sp-card" data-district="ex">')
        lines.append(f'              <span class="councilor-badge" style="background: rgba(13, 148, 136, 0.1); color: #0d9488">{esc(pos)}</span>')
        lines.append(f'              <h3 class="councilor-name" style="font-size: 1.125rem; margin: 8px 0 4px">Hon. {esc(name)}</h3>')
        lines.append(f'              <p class="councilor-committees" style="font-size: 0.8125rem; color: var(--color-text-light)">')
        lines.append(f'                Sangguniang Panlalawigan &bull; {esc(pos)}')
        lines.append('              </p>')
        if verif:
            lines.append(f'              <div style="font-size: 0.75rem; color: var(--color-text-light); border-top: 1px solid rgba(0,0,0,0.05); padding-top: 6px; margin-top: 8px"><i class="bi bi-check-circle" style="color: var(--color-success)"></i> {esc(verif)}</div>')
        lines.append('            </div>')
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </section>')
    lines.append('')
    lines.append('      <!-- Section 4: Cities & Municipalities Directory -->')
    lines.append('      <section class="section" id="lgu-officials-directory">')
    lines.append('        <div class="container">')
    lines.append('          <div class="text-center" style="margin-bottom: var(--spacing-xl)">')
    lines.append('            <span class="gov-section-badge">')
    lines.append('              <i class="bi bi-diagram-3-fill"></i> <span data-i18n="gov-badge-local-governance">Local Governance</span>')
    lines.append('            </span>')
    lines.append('            <h2 style="font-size: 1.75rem; margin-bottom: var(--spacing-xs)" data-i18n="gov-section-lgu-heading">')
    lines.append('              Cities &amp; Municipalities Directory')
    lines.append('            </h2>')
    lines.append('            <p style="color: var(--color-text-light)" data-i18n="gov-section-lgu-desc">')
    lines.append('              Elected Mayors, Vice Mayors, and Councilors across all 18 local government units of Albay')
    lines.append('            </p>')
    lines.append('          </div>')
    lines.append('')
    # Toolbar
    lines.append('          <div class="dir-toolbar">')
    lines.append('            <div class="dir-toolbar-row">')
    lines.append('              <div class="dir-field dir-search-field">')
    lines.append('                <label class="dir-field-label" for="lgu-search-input" data-i18n="gov-search-label">Search Directory</label>')
    lines.append('                <div class="dir-search-input-wrap">')
    lines.append('                  <i class="bi bi-search" aria-hidden="true"></i>')
    lines.append(
        '                  <input class="dir-input" id="lgu-search-input" type="search" placeholder="City, municipality, mayor, vice mayor, or councilor name…" data-i18n-placeholder="gov-search-placeholder" autocomplete="off" aria-describedby="lgu-results-count" />'
    )
    lines.append('                </div>')
    lines.append('              </div>')
    lines.append('              <div class="dir-field dir-field-type">')
    lines.append('                <label class="dir-field-label" for="lgu-type-select" data-i18n="gov-filter-class-label">LGU Classification</label>')
    lines.append('                <select class="dir-select" id="lgu-type-select">')
    lines.append('                  <option value="all" data-i18n="gov-filter-all-lgus">All LGUs (18)</option>')
    lines.append('                  <option value="city" data-i18n="gov-filter-cities-only">Cities only (3)</option>')
    lines.append('                  <option value="municipality" data-i18n="gov-filter-mun-only">Municipalities only (15)</option>')
    lines.append('                </select>')
    lines.append('              </div>')
    lines.append('              <div class="dir-field dir-field-district">')
    lines.append('                <label class="dir-field-label" for="lgu-district-select" data-i18n="gov-filter-district-label">District</label>')
    lines.append('                <select class="dir-select" id="lgu-district-select">')
    lines.append('                  <option value="all" data-i18n="gov-filter-all-districts">All Districts (3)</option>')
    lines.append('                  <option value="1" data-i18n="gov-filter-d1-lgus">1st District (6 LGUs)</option>')
    lines.append('                  <option value="2" data-i18n="gov-filter-d2-lgus">2nd District (5 LGUs)</option>')
    lines.append('                  <option value="3" data-i18n="gov-filter-d3-lgus">3rd District (7 LGUs)</option>')
    lines.append('                </select>')
    lines.append('              </div>')
    lines.append('              <div class="dir-field dir-field-action">')
    lines.append('                <button type="button" class="btn btn-secondary btn-compact" id="lgu-reset-btn">')
    lines.append('                  <i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i> <span data-i18n="gov-btn-reset">Reset</span>')
    lines.append('                </button>')
    lines.append('              </div>')
    lines.append('            </div>')
    lines.append('            <div class="dir-toolbar-foot">')
    lines.append(f'              <p class="dir-count" id="lgu-results-count" role="status" aria-live="polite">Showing {total_lgus} of {total_lgus} LGUs</p>')
    lines.append('              <div class="dir-actions">')
    lines.append('                <a href="barangays.html" class="btn btn-secondary btn-compact"><i class="bi bi-signpost-split"></i> <span data-i18n="gov-link-barangays">Albay 720 Barangays</span></a>')
    lines.append('              </div>')
    lines.append('            </div>')
    lines.append('          </div>')
    lines.append('')
    # Empty Notice
    lines.append('          <div class="dir-empty" id="lgu-empty-notice" hidden>')
    lines.append('            <i class="bi bi-search" aria-hidden="true"></i>')
    lines.append('            <p data-i18n="gov-empty-notice">No local government unit or official matches your filter criteria. Try adjusting the search term or resetting the filters.</p>')
    lines.append('          </div>')
    lines.append('')
    # LGU Grid
    lines.append('          <div id="lgu-grid" class="lgu-grid">')

    # All LGUs combined (cities first, then municipalities alphabetically)
    all_lgus = []
    for c in cities:
        all_lgus.append({"data": c, "is_city": True})
    for m in municipalities:
        all_lgus.append({"data": m, "is_city": False})

    # Sort: cities first, then by name
    all_lgus.sort(key=lambda x: (0 if x["is_city"] else 1, x["data"]["name"]))

    for item in all_lgus:
        lgu = item["data"]
        is_city = item["is_city"]
        name = lgu.get("name", "")
        clean_name = name.replace(" City", "") if is_city else name
        district = LGU_DISTRICTS.get(name, LGU_DISTRICTS.get(clean_name, 1))
        is_capital = "Legazpi" in name

        mayor = lgu.get("mayor", {})
        mayor_name = mayor.get("name", "Unlisted")
        vm = lgu.get("vice_mayor", {})
        vm_name = vm.get("name", "Unlisted")

        councilors = lgu.get("city_councilors", []) if is_city else lgu.get("municipal_councilors", [])
        c_count = len(councilors)

        # Build comprehensive search corpus including roles, titles, district variants and officials
        councilor_names = [c.get("name", "") for c in councilors]
        ord_text = DISTRICT_ORDINALS.get(district, "")
        role_keywords = "mayor vice mayor city mayor municipal mayor councilor councilors city councilor municipal councilor sanggunian member kagawad"
        class_keywords = "city cities sangguniang panlungsod" if is_city else "municipality municipalities town sangguniang bayan"
        capital_keywords = "capital provincial capital" if is_capital else ""

        search_corpus = (
            f"{name} {clean_name} {class_keywords} {capital_keywords} {role_keywords} "
            f"{mayor_name} {vm_name} {' '.join(councilor_names)} "
            f"district {district} district{district} {ord_text} district"
        ).lower()

        lines.append(
            f'            <article class="lgu-card" data-name="{esc(name)}" data-type="{"city" if is_city else "municipality"}" data-district="{district}" data-corpus="{esc(search_corpus)}">'
        )
        lines.append('              <div class="lgu-head">')
        lines.append(
            f'                <div class="lgu-mark{" capital" if is_capital else ""}">'
            f'<i class="bi bi-{"building" if is_city else "geo-alt"}"></i></div>'
        )
        lines.append('                <div>')
        lines.append(f'                  <h3 class="lgu-name">{esc(name)}</h3>')
        lines.append('                  <div class="lgu-pills">')
        if is_city:
            lines.append('                    <span class="pill pill-city">City</span>')
        else:
            lines.append('                    <span class="pill pill-municipality">Municipality</span>')
        if is_capital:
            lines.append('                    <span class="pill pill-capital">Capital</span>')
        lines.append(f'                    <span class="pill pill-code">District {district}</span>')
        lines.append('                  </div>')
        lines.append('                </div>')
        lines.append('              </div>')
        lines.append('')
        lines.append('              <div class="lead-pair">')
        lines.append('                <div class="lead-role">')
        lines.append('                  <i class="bi bi-person-badge" style="color: var(--color-primary)"></i>')
        lines.append(f'                  <span>{"City" if is_city else "Municipal"} Mayor: <strong>Hon. {esc(mayor_name)}</strong></span>')
        lines.append('                </div>')
        lines.append('                <div class="lead-role">')
        lines.append('                  <i class="bi bi-person" style="color: var(--color-primary)"></i>')
        lines.append(f'                  <span>Vice Mayor: <strong>Hon. {esc(vm_name)}</strong></span>')
        lines.append('                </div>')
        lines.append('              </div>')
        lines.append('')
        # Councilors section — accessible <details> / <summary> with no-JS fallback
        lines.append('              <details class="councilors-collapse">')
        lines.append(
            f'                <summary class="council-toggle-btn" data-count="{c_count}" aria-expanded="false">'
            f'<i class="bi bi-people"></i> <span>View Councilors ({c_count})</span> <i class="bi bi-chevron-down toggle-icon"></i></summary>'
        )
        lines.append('                <div class="councilor-tag-list">')
        for c in councilors:
            cname = c.get("name", "")
            lines.append(f'                  <span class="councilor-tag" data-official="{esc(cname.lower())}">Hon. {esc(cname)}</span>')
        lines.append('                </div>')
        lines.append('              </details>')
        lines.append('')
        # Footer links
        lines.append('              <div class="lgu-links">')
        lines.append(
            f'                <a href="barangays.html?lgu={esc(clean_name)}"><i class="bi bi-diagram-3"></i> <span data-i18n="gov-btn-barangays">Barangays</span></a>'
        )
        lines.append('                <a href="../statistics/"><i class="bi bi-graph-up"></i> <span data-i18n="gov-btn-stats">Statistics</span></a>')
        lines.append('              </div>')
        lines.append('            </article>')

    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </section>')
    lines.append('')
    # Section 5: Sources & Verification
    lines.append('      <!-- Section 5: Sources & Verification -->')
    lines.append('      <section class="section" id="transparency-provenance" style="background: var(--color-bg-alt)">')
    lines.append('        <div class="container">')
    lines.append('          <div class="text-center" style="max-width: 860px; margin: 0 auto var(--spacing-lg)">')
    lines.append('            <span class="gov-section-badge"><i class="bi bi-shield-check"></i> <span data-i18n="gov-sources-heading">Official Sources &amp; Transparency</span></span>')
    lines.append('            <h2 style="font-size: 1.75rem; margin-bottom: var(--spacing-xs)" data-i18n="gov-sources-title">Information Transparency &amp; Provenance</h2>')
    lines.append('            <p style="font-size: 0.95rem; color: var(--color-text-light); line-height: 1.6" data-i18n="gov-sources-desc">')
    lines.append(
        '              Data on this page is compiled from public directories and verifiable government records. '
        'BetterAlbay is an independent civic tech project under <a href="https://bettergov.ph/" target="_blank" rel="noopener noreferrer">BetterGov.ph</a>.'
    )
    lines.append('            </p>')
    lines.append('          </div>')
    lines.append('')
    lines.append('          <div class="grid grid-2" style="gap: var(--spacing-lg); max-width: 1060px; margin: 0 auto">')
    # Source Pointers Box
    lines.append('            <div class="rep-card" style="padding: 24px">')
    lines.append('              <h3 style="font-size: 1.125rem; margin-top: 0; display: flex; align-items: center; gap: 8px">')
    lines.append('                <i class="bi bi-link-45deg" style="color: var(--color-primary)"></i> <span data-i18n="gov-source-pointers">Official Source Pointers</span>')
    lines.append('              </h3>')
    lines.append('              <ul style="font-size: 0.875rem; color: var(--color-text); line-height: 1.7; padding-left: 1.25rem; margin-bottom: 0">')
    lines.append('                <li><a href="https://www.congress.gov.ph/" target="_blank" rel="noopener noreferrer">House of Representatives (20th Congress)</a> — Congressional district representatives.</li>')
    lines.append('                <li><a href="https://albay.gov.ph/" target="_blank" rel="noopener noreferrer">Provincial Government of Albay</a> — Provincial Governor, Vice Governor, and Provincial Board.</li>')
    lines.append('                <li><a href="https://dilg.gov.ph/barangay-officials-directory" target="_blank" rel="noopener noreferrer">DILG Barangay Officials Directory</a> — Village-level leadership listings.</li>')
    gdrive_url = source_pointers.get("local_officials_directory", "https://drive.google.com/drive/folders/1fcyeVj_aNF3mdcnDq8rvL8Zj9r77oLZw")
    lines.append(f'                <li><a href="{esc(gdrive_url)}" target="_blank" rel="noopener noreferrer">DILG Local Officials Archive</a> — Municipal and city official profiles.</li>')
    lines.append('                <li><a href="https://www.comelec.gov.ph/" target="_blank" rel="noopener noreferrer">Commission on Elections (COMELEC)</a> — Official election returns and proclamations.</li>')
    lines.append('              </ul>')
    lines.append('            </div>')
    # Scope & Limitations Box
    lines.append('            <div class="rep-card" style="padding: 24px">')
    lines.append('              <h3 style="font-size: 1.125rem; margin-top: 0; display: flex; align-items: center; gap: 8px">')
    lines.append('                <i class="bi bi-info-circle" style="color: #0284c7"></i> <span data-i18n="gov-scope-limitations">Scope &amp; Limitations Notice</span>')
    lines.append('              </h3>')
    lines.append('              <ul style="font-size: 0.875rem; color: var(--color-text-light); line-height: 1.6; padding-left: 1.25rem; margin-bottom: 0">')
    for lim in limitations:
        lines.append(f'                <li>{esc(lim)}</li>')
    lines.append('                <li>Looking for village data? Explore our dedicated <a href="barangays.html">Albay Barangay Directory</a>.</li>')
    lines.append('              </ul>')
    lines.append('            </div>')
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </section>')
    lines.append('    </main>')
    lines.append('')
    # Footer
    lines.append('    <!-- Footer -->')
    lines.append('    <footer class="site-footer">')
    lines.append('      <div class="container">')
    lines.append('        <div class="footer-main-new">')
    lines.append('          <div class="footer-brand">')
    lines.append('            <img')
    lines.append('              src="../assets/images/logo/better-albay-logo-text-white.svg"')
    lines.append('              alt="Better Albay logo"')
    lines.append('              class="footer-logo"')
    lines.append('            />')
    lines.append('            <p class="footer-tagline" data-i18n="gov-empowering-the-people-of-albay-with-transparent">')
    lines.append('              Empowering the people of Albay with transparent access to the services, programs, and public funds of LGU Albay.')
    lines.append('            </p>')
    lines.append('            <div class="footer-social-new">')
    lines.append('              <a href="https://www.facebook.com/pioalbay2023" class="footer-social-btn" target="_blank" rel="noopener noreferrer" aria-label="Facebook"><i class="bi bi-facebook"></i></a>')
    lines.append('              <a href="https://www.linkedin.com/company/betteralbay/" class="footer-social-btn" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn"><i class="bi bi-linkedin"></i></a>')
    lines.append('              <a href="https://discord.com/invite/qeSu7RJkjQ" class="footer-social-btn" target="_blank" rel="noopener noreferrer" aria-label="Discord"><i class="bi bi-discord"></i></a>')
    lines.append('            </div>')
    lines.append('          </div>')
    lines.append('          <div class="footer-column">')
    lines.append('            <h4 data-i18n="gov-quick-links">Quick Links</h4>')
    lines.append('            <ul class="footer-links-new">')
    lines.append('              <li><a href="https://albay.gov.ph/">Official Albay government website</a></li>')
    lines.append('              <li><a href="https://albay.gov.ph/wp-content/uploads/2025/10/As-of-October-21-2025-2.pdf" target="_blank" rel="noopener noreferrer" data-i18n="gov-citizens-charter">Citizen\'s Charter</a></li>')
    lines.append('              <li><a href="../terms/" data-i18n="gov-terms-of-use">Terms of Use</a></li>')
    lines.append('              <li><a href="../privacy/" data-i18n="gov-privacy-policy">Privacy Policy</a></li>')
    lines.append('              <li><a href="../accessibility/" data-i18n="gov-accessibility">Accessibility</a></li>')
    lines.append('              <li><a href="../faq/">FAQ</a></li>')
    lines.append('            </ul>')
    lines.append('          </div>')
    lines.append('          <div class="footer-column">')
    lines.append('            <h4 data-i18n="gov-resources">Resources</h4>')
    lines.append('            <ul class="footer-links-new">')
    lines.append('              <li><a href="https://data.gov.ph" target="_blank" rel="noopener noreferrer" data-i18n="gov-open-data-philippines">Open Data Philippines</a></li>')
    lines.append('              <li><a href="https://www.foi.gov.ph/" target="_blank" rel="noopener noreferrer" data-i18n="gov-freedom-of-information">Freedom of Information</a></li>')
    lines.append('              <li><a href="barangays.html">Barangay Directory</a></li>')
    lines.append('              <li><a href="officials.html">Elected Officials (CMCI)</a></li>')
    lines.append('              <li><a href="../statistics/">Statistics &amp; Demographics</a></li>')
    lines.append('            </ul>')
    lines.append('          </div>')
    lines.append('          <div class="footer-column footer-column-actions">')
    lines.append('            <div class="footer-cost" role="status" aria-label="Cost to the People of Albay: Zero Pesos">')
    lines.append('              <span>Cost to the People of Albay =</span> <span class="footer-cost-value">₱0</span>')
    lines.append('            </div>')
    lines.append('            <a href="mailto:volunteer@betteralbay.org" class="footer-contribute">')
    lines.append('              <i class="bi bi-envelope" aria-hidden="true"></i> <span data-i18n="gov-volunteer-with-us">Volunteer with us</span>')
    lines.append('            </a>')
    lines.append('            <a href="https://github.com/jsonrls/better-albay" class="footer-contribute" target="_blank" rel="noopener noreferrer">')
    lines.append('              <i class="bi bi-github" aria-hidden="true"></i> <span>Contribute code with us</span>')
    lines.append('            </a>')
    lines.append('            <div class="footer-partners">')
    lines.append('              <a href="https://abakada.org" target="_blank" rel="noopener noreferrer" aria-label="Abakada.org">')
    lines.append('                <img src="../assets/images/logo/abakada-footer.svg" alt="Abakada.org" class="footer-partner-logo" width="48" height="38" loading="lazy" />')
    lines.append('              </a>')
    lines.append('              <a href="https://hivcareph.org/" target="_blank" rel="noopener noreferrer" aria-label="HIV Care Philippines">')
    lines.append('                <img src="../assets/images/logo/hiv-care-logo-footer.svg" alt="HIV Care Philippines" class="footer-partner-logo" width="48" height="38" loading="lazy" />')
    lines.append('              </a>')
    lines.append('              <a href="https://bettergov.ph" target="_blank" rel="noopener noreferrer" aria-label="BetterGov.ph">')
    lines.append('                <img src="../assets/images/logo/bettergov-footer.svg" alt="BetterGov.ph" class="footer-partner-logo" width="48" height="38" loading="lazy" />')
    lines.append('              </a>')
    lines.append('            </div>')
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('        <div class="footer-bottom-new">')
    lines.append('          <div class="footer-copyright">')
    lines.append('            <span class="footer-copyright-text">&copy; 2026 BetterAlbay.org</span>')
    lines.append('            <span class="footer-copyright-license">MIT | CC BY 4.0</span>')
    lines.append('            <span class="footer-copyright-disclaimer">An independent civic tech project. A member of BetterGov.ph. For official records, visit albay.gov.ph.</span>')
    lines.append('            <span class="footer-version"><i class="bi bi-boxes"></i> Ver. 1.1.30</span>')
    lines.append('          </div>')
    lines.append('        </div>')
    lines.append('      </div>')
    lines.append('    </footer>')
    lines.append('')
    lines.append('    <script defer src="../assets/js/translations.js"></script>')
    lines.append('    <script defer src="../assets/js/info-bar.js"></script>')
    lines.append('    <script defer src="../assets/js/main.js"></script>')
    lines.append('    <script defer src="../assets/js/government.js"></script>')
    lines.append('    <script defer src="../assets/js/version.js"></script>')
    lines.append('  </body>')
    lines.append('</html>')
    lines.append('')

    content = '\n'.join(lines)
    with open(TARGET_PATH, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f'Successfully built {TARGET_PATH} ({len(content)} bytes)')

    # Auto-stamp assets so page remains in sync with CI asset stamp check
    try:
        subprocess.run(['node', str(ROOT / 'scripts' / 'stamp-assets.js')], check=True, cwd=ROOT)
        print('Successfully stamped asset hashes.')
    except Exception as e:
        print(f'Note: stamp-assets.js could not be automatically invoked: {e}')


if __name__ == '__main__':
    build_page()
