#!/usr/bin/env python3
"""
Point every page footer at the white-wordmark logo variant.

The footer sits on a dark gradient (assets/css/footer.css -> #1a1a1a -> #111111),
but its <img> used the same dark-wordmark file as the header, so the wordmark
was nearly invisible against its own background.

This rewrites *only* the <img> tags that carry class="footer-logo" to use
`better-albay-logo-text-white.svg` (generated by scripts/make-logo-text-white.py,
which recolours the wordmark paths and leaves the Mayon/sun icon untouched).
The header (class="logo-img") and the volunteer popup (class="vol-popup-logo")
keep the original artwork.

Idempotent: re-running changes nothing and still exits 0.

    python3 scripts/set-footer-logo.py            # dry run (default)
    python3 scripts/set-footer-logo.py --write    # apply
    python3 scripts/set-footer-logo.py --check    # exit 1 if any file is stale (CI)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

DARK_LOGO = "better-albay-logo.svg"
WHITE_LOGO = "better-albay-logo-text-white.svg"

# The footer <img> is the only thing we touch, and only on lines that carry the
# footer class. `logo-img` (header) and `vol-popup-logo` also sit on the page.
FOOTER_CLASS = 'class="footer-logo"'
# Negative lookbehind on "-text-white" keeps a second run a no-op.
LOGO_REF = re.compile(r"(?<!-text-white/)better-albay-logo\.svg")

# Build outputs and vendored trees are not sources.
SKIP_DIRS = {"node_modules", "dist", "out", ".next", ".git", "test-results", "playwright-report"}


def html_files():
    for file in sorted(ROOT.rglob("*.html")):
        if SKIP_DIRS & set(file.relative_to(ROOT).parts):
            continue
        yield file


def rewrite(text):
    """Return (new_text, changed_line_count)."""
    lines = text.splitlines(keepends=True)
    changed = 0
    for i, line in enumerate(lines):
        if FOOTER_CLASS not in line:
            continue
        new_line = LOGO_REF.sub(WHITE_LOGO, line)
        if new_line != line:
            lines[i] = new_line
            changed += 1
    return "".join(lines), changed


def main():
    args = set(sys.argv[1:])
    write = "--write" in args
    check = "--check" in args

    asset = ROOT / "assets/images/logo" / WHITE_LOGO
    if not asset.exists():
        sys.exit(f"missing asset: {asset.relative_to(ROOT)} - run scripts/make-logo-text-white.py first")

    stale, touched = [], 0
    for file in html_files():
        source = file.read_text(encoding="utf-8")
        if DARK_LOGO not in source:
            continue
        updated, changed = rewrite(source)
        if not changed:
            continue
        rel = file.relative_to(ROOT)
        stale.append(f"{rel}: {changed} footer logo reference(s) -> {WHITE_LOGO}")
        if write:
            file.write_text(updated, encoding="utf-8")
            touched += 1

    if check:
        if stale:
            print("\n".join(stale))
            sys.exit(f"\n{len(stale)} file(s) still point the footer at the dark logo. "
                     f"Run: python3 scripts/set-footer-logo.py --write")
        print("footer logo: all current")
        return

    if not stale:
        print("footer logo: all current")
        return

    print("\n".join(stale))
    if write:
        print(f"\nfooter logo: updated {len(stale)} reference(s) across {touched} file(s)")
    else:
        print(f"\nfooter logo: {len(stale)} file(s) would change. Re-run with --write to apply.")


if __name__ == "__main__":
    main()
